version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
  db:
    image: postgres:9
    volumes:
      - db_store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
volumes:
  db_store:
